name: CI

on: [push]

jobs:
  run_tests:
    name: Python-Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pip
        run: pip install -r requirements/pip.txt

      - name: Install Dependencies
        run: pip install -r requirements/ci.txt

      - name: Install quality equirements
        run: pip install -r ./requirements/quality.txt

      - name: Run black formatter
        run: black --check .

      - name: Run pylint
        run: pylint edx_username_changer test_utils tests

      - name: Run Tests
        run: pytest test_utils tests

      - name: Run coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
